---
title: "My first dashboard: Childcare inspections"
output: 
    flexdashboard::flex_dashboard:
      orientation: rows
---

Headline Figures
========================================================================

```{r setup, include=FALSE}
library(flexdashboard); library(tidyverse); library(plotly); library(dygraphs); library(xts); library(padr)

cc_data<- read.csv("Childcare_provider_data_Ofsted_Dec2017.csv",
                   header = TRUE )
```

Row
-----------------------------------------------------------------------

### My favourite number

```{r}
valueBox(10, icon = "fa-certificate")
```

### Most registered places

```{r}
most_places<- max(cc_data$Registered.places)

valueBox(most_places, icon = "fa-bullhorn", color = "purple")
```


### Overall outcome good or outstanding

```{r}
rate <- round((9315+39940) / 52878 *100 ,2)
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


Row {.tabset}
-----------------------------------------------------------------------

### Childcare market composition  Dec 2017

```{r, fig.height= 6, fig.width=12}

my_graph<- ggplot(data = cc_data) +
  geom_bar(aes(x = Provider.Type, fill = Provider.Type), stat = "count")+
  theme_bw()+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggplotly(my_graph)
```

### Number of places by childcare provider

```{r}
my_graph2<- ggplot(data = cc_data) +
  geom_histogram(aes(x = Registered.places, fill = Provider.Type))+
  facet_wrap(~Provider.Type, scales = "free")+
  guides(fill=FALSE)+
  theme_bw()

my_graph2

```


### Overall effectivness by Chilcare provider
```{r}

# filter and pipe into ggplot using dplyr to provide a graphical breakdown
my_graph3<- cc_data %>% filter(Most.recent.full.EYR.inspection...Overall.effectiveness != "NULL") %>%
  mutate(Most.recent.full.EYR.inspection...Overall.effectiveness = as.numeric(as.character(Most.recent.full.EYR.inspection...Overall.effectiveness))) %>%
  ggplot(.) +
  geom_histogram(aes(x = Most.recent.full.EYR.inspection...Overall.effectiveness, fill = Provider.Type))+
  facet_wrap(~Provider.Type, scales = "free")+
  guides(fill=FALSE)+
  labs(x = "Overall effectiveness rating")+
  theme_bw()

my_graph3

```


Temporal
=========================================================================


Inputs {.sidebar}
-------------------------------------

I'm a sidebar with some information.

You can put details such as who you are:

**Built by**: Kerry cella

And where to contact you here:

**Contact**: kerry.cella@education.gov.uk

Row
-------------------------------------

### Dates of inspections

```{r}
# create data frame for inspections by date
dates_of_inspections <- cc_data %>% count(Most.recent.full.EYR.inspection.date) %>%
  mutate(Most.recent.full.EYR.inspection.date = as.Date(as.character(Most.recent.full.EYR.inspection.date))) %>%
  filter(!is.na (Most.recent.full.EYR.inspection.date),
         Most.recent.full.EYR.inspection.date > "2017-01-01") %>%
  #pad out missing values using padr
  pad(.) %>% mutate(n = ifelse(is.na(n), 0, n))

#convert to xts as it plays nicely with dygprah
xts_dos<- xts(x = dates_of_inspections$n, order.by = dates_of_inspections$Most.recent.full.EYR.inspection.date)

#plot our dygraph
dygraph(xts_dos) %>%
  dyOptions(includeZero = TRUE) %>% dySeries("V1", label = "Number of inspections")

```

